services:
  - type: web
    name: NextJS App Deploy
    region: frankfurt
    runtime: node
    plan: free
    buildCommand: npm i && npm run build:demonextjs
    startCommand: npm run start:demonextjs
    branch: master
    envVars:
      - key: NEXT_PUBLIC_EDITOR_URL
        value: https://cdn.brizylocal.com/pages/3.1.9/index.js
      - key: NEXT_PUBLIC_EDITOR_ICON_URL
        value: https://cdn.brizylocal.com/pages/3.1.9/dist/free/editor/icons
      - key: NEXT_PUBLIC_EDITOR_TOKEN
        value: demo
      - key: NEXT_PUBLIC_APP_PURCHASE_URL
        value: https://brizy.io
      - key: NEXT_PUBLIC_APP_PREVIEW_DOCS_URL
        value: https://brizy.io
      - key: MONGODB_DATABASE_NAME
        value: brizy # Possible to be: "netlify" | "render"
      - key: MONGODB_URI
        value: mongodb+srv://guest:NOczraPgpfXCcwFm@brizy.bhrbdoy.mongodb.net/?retryWrites=true&w=majority&appName=brizy
      - key: SHOPIFY_STORE_URL
        value: https://abracadabra20.myshopify.com
      - key: SHOPIFY_ACCESS_TOKEN
        value: 3b47750ab922efb31d3e7d268ed3ea93
      - key: NODE_VERSION
        value: 18.20.3
