export enum PlaceholderType {
  NavItem = "nav_item",
  Translation = "translation_switcher",
  Builder = "placeholder",
  RandomId = "random_id",
  Group = "group",
  MenuLoop = "menu_loop",
  MenuTitle = "menu_title",
  MenuItemTitle = "menu_item_title",
  MenuItemIcon = "menu_item_icon",
  MenuItemIconValue = "menu_item_icon_value",
  MenuUrl = "menu_url",
  MenuAttributes = "menu_attributes",
  MenuItemAttributes = "menu_item_attributes",
  MenuLoopSubmenu = "menu_loop_submenu",
  MegaMenu = "mega_menu",
  MegaMenuValue = "mega_menu_value",
}
