version: '3.8'

services:
  image_resizer:
    container_name: image_resizer
    image: image_resizer:latest
    environment:
      APP_ENV: 'dev'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: ./
    volumes:
      - ./:/project
