import { EntityType } from "@/constants/EntityType";
import type { Config } from "@/hooks/useEditor/types";
import { PlaceholderType } from "@/placeholders/types/types";
import { DCTypes } from "@builder/core/build/es/types/dynamicContent";
import { Menu } from "@builder/core/build/es/types/menu";
import { Modes } from "@builder/core/build/es/types/types";
import { Help } from "@builder/core/build/es/types/types";

export const demoMenu: Menu = [
  {
    id: "5e8cc6634f6e2ee93b5137f134685896",
    name: "Main Menu Top",
    items: [
      {
        type: "MenuItem",
        value: {
          id: "da9dc0e53e7825c429ca9b22be1fa2cc",
          url: "#",
          title: "Features",
          items: [
            {
              type: "MenuItem",
              value: {
                id: "413bff0e7a88eba33d250ac3ae99166a",
                url: "/previews",
                title: "Previews",
              },
            },
            {
              type: "MenuItem",
              value: {
                id: "2238dcd350ec2811d824ddfe546667ce",
                url: "/analytics",
                title: "Analytics",
              },
            },
            {
              type: "MenuItem",
              value: {
                id: "0783e8be271654da41071e1be23d10a3",
                url: "/edge",
                title: "Edge",
              },
            },
            {
              type: "MenuItem",
              value: {
                id: "3342071ce73ad1dbee9f560392da2549",
                url: "/nextjs",
                title: "Nextjs",
              },
            },
            {
              type: "MenuItem",
              value: {
                id: "0c0d9ec288588ccb2ae77c2d16996b2b",
                url: "/customers",
                title: "Infrastructure",
              },
            },
            {
              type: "MenuItem",
              value: {
                id: "1f3b2eb7b9d89c1bc438af7b5a5f5e7e",
                url: "/storage",
                title: "Storage",
              },
            },
          ],
        },
      },
      {
        type: "MenuItem",
        value: {
          id: "b664a1d33ab23a4cff2a98f5b759104e",
          url: "/integrations",
          title: "Integrations",
        },
      },
      {
        type: "MenuItem",
        value: {
          id: "f912e97e0ad9e83b7961445e3d2bc216",
          url: "/customers",
          title: "Customers",
        },
      },
      {
        type: "MenuItem",
        value: {
          id: "1709f54f60608c3c74ac63f08b2e657e",
          url: "/enterprise",
          title: "Enterprise",
        },
      },
      {
        type: "MenuItem",
        value: {
          id: "c513518d193e85fca4ce274368792dd2",
          url: "/pricing",
          title: "Pricing",
        },
      },
      {
        type: "MenuItem",
        value: {
          id: "f28b0d24849fedf1bdda5be865b76fae",
          url: "/contact",
          title: "Contact",
        },
      },
    ],
  },
];

const helpVideos: Help = {
  video: [
    {
      id: "0c",
      category: "Get Started",
      items: [
        {
          title: "Builder Overview",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/1.+GET+STARTED/1.+Builder+Overview.mp4",
          id: "0",
        },
        {
          title: "How to Build a Page",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/1.+GET+STARTED/2.+How+to+Build+a+Page.mp4",
          id: "1",
        },
        {
          title: "Preview Publish Update",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/1.+GET+STARTED/3.+Preview+Publish+Update.mp4",
          id: "2",
        },
      ],
    },
    {
      id: "1c",
      category: "The Basics",
      items: [
        {
          title: "Blocks",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/2.+THE+BASICS/1.+Blocks.mp4",
          id: "3",
        },
        {
          title: "Saved Blocks & Layouts",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/2.+THE+BASICS/2.+Saved+Blocks+&+Layouts.mp4",
          id: "4",
        },
        {
          title: "Premade Layouts",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/2.+THE+BASICS/3.+Premade+Layouts.mp4",
          id: "5",
        },
        {
          title: "The Elements",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/2.+THE+BASICS/4.+The+Elements.mp4",
          id: "6",
        },
        {
          title: "Reorder Blocks",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/2.+THE+BASICS/5.+Reorder+Blocks.mp4",
          id: "7",
        },
        {
          title: "Global Styling",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/2.+THE+BASICS/6.+Global+Styling.mp4",
          id: "8",
        },
        {
          title: "Links",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/2.+THE+BASICS/7.+Links.mp4",
          id: "9",
        },
        {
          title: "Fonts",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/2.+THE+BASICS/8.+Fonts.mp4",
          id: "10",
        },
        {
          title: "Paddings & Margins",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/2.+THE+BASICS/9.+Padding+&+Margins.mp4",
          id: "11",
        },
        {
          title: "Responsive Design",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/2.+THE+BASICS/10.+Responsive+Design.mp4",
          id: "12",
        },
        {
          title: "Headers & Footers",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/2.+THE+BASICS/11.+Headers+&+Footers.mp4",
          id: "13",
        },
        {
          title: "Menus & Navigation",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/2.+THE+BASICS/12.+Menus+&+Navigation.mp4",
          id: "14",
        },
        {
          title: "Global Blocks",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/2.+THE+BASICS/13.+Global+Blocks.mp4",
          id: "15",
        },
        {
          title: "Animations",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/2.+THE+BASICS/14.+Animations.mp4",
          id: "16",
        },
        {
          title: "Multilingual",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/2.+THE+BASICS/15.+Multilingual.mp4",
          id: "17",
        },
      ],
    },
    {
      id: "2c",
      category: "Dynamic Content",
      items: [
        {
          title: "Blogging",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/3.+DYNAMIC+CONTENT/1.+Blogging.mp4",
          id: "18",
        },
        {
          title: "Dynamic Elements",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/3.+DYNAMIC+CONTENT/2.+Dynamic+Elements.mp4",
          id: "19",
        },
        {
          title: "Dynamic Templates",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/3.+DYNAMIC+CONTENT/3.+Dynamic+Templates.mp4",
          id: "20",
        },
        {
          title: "Advanced Custom Fields & Assets",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/3.+DYNAMIC+CONTENT/4.+Advanced+Custom+Fields+&+Assets.mp4",
          id: "21",
        },
      ],
    },
    {
      id: "3c",
      category: "Users & Membership",
      items: [
        {
          title: "Users & Roles",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/4.+USERS+&+MEMBERSHIP/1.+Users+&+Roles.mp4",
          id: "22",
        },
        {
          title: "Membership Blocks",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/4.+USERS+&+MEMBERSHIP/2.+Membership+Blocks.mp4",
          id: "23",
        },
      ],
    },
    {
      id: "4c",
      category: "Marketing Tools",
      items: [
        {
          title: "Popup Builder",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/5.+MARKETING+TOOLS/1.+Popup+Builder.mp4",
          id: "24",
        },
        {
          title: "Global Popups & Triggers",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/5.+MARKETING+TOOLS/2.+Global+Popups+&+Triggers.mp4",
          id: "25",
        },
        {
          title: "Contact Form & Integrations",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/5.+MARKETING+TOOLS/3.+Contact+Form+&+Integrations.mp4",
          id: "26",
        },
        {
          title: "Web Stories",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/5.+MARKETING+TOOLS/4.+Web+Stories.mp4",
          id: "27",
        },
      ],
    },
    {
      id: "5c",
      category: "Global Settings",
      items: [
        {
          title: "SEO",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/6.+GLOBAL+SETTINGS/1.+SEO.mp4",
          id: "28",
        },
        {
          title: "Social Sharing",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/6.+GLOBAL+SETTINGS/2.+Social+Sharing.mp4",
          id: "29",
        },
        {
          title: "Custom CSS",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/6.+GLOBAL+SETTINGS/3.+Custom+CSS.mp4",
          id: "30",
        },
        {
          title: "Code Inject",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/6.+GLOBAL+SETTINGS/4.+Code+Inject.mp4",
          id: "31",
        },
        {
          title: "Redirects",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/6.+GLOBAL+SETTINGS/5.+Redirects.mp4",
          id: "32",
        },
        {
          title: "System Pages",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/6.+GLOBAL+SETTINGS/6.+System+Pages.mp4",
          id: "33",
        },
      ],
    },
    {
      id: "6c",
      category: "Cool Features",
      items: [
        {
          title: "Shortcuts",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/7.+COOL+FEATURES/1.+Shortcuts.mp4",
          id: "34",
        },
        {
          title: "Webhooks",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/7.+COOL+FEATURES/2.+Webhooks.mp4",
          id: "35",
        },
        {
          title: "Export & Import",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/7.+COOL+FEATURES/3.+Export+&+Import.mp4",
          id: "36",
        },
        {
          title: "Collaborate",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/7.+COOL+FEATURES/4.+Collaborate.mp4",
          id: "37",
        },
      ],
    },
    {
      id: "7c",
      category: "The Elements",
      items: [
        {
          title: "Rows & Columns",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/1.+Rows+&+Columns.mp4",
          id: "38",
        },
        {
          title: "Text",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/2.+Text.mp4",
          id: "39",
        },
        {
          title: "Button",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/3.+Button.mp4",
          id: "40",
        },
        {
          title: "Icon",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/4.+Icon.mp4",
          id: "41",
        },
        {
          title: "Image",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/5.+Image.mp4",
          id: "42",
        },
        {
          title: "Audio",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/6.+Audio.mp4",
          id: "43",
        },
        {
          title: "Video",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/7.+Video.mp4",
          id: "44",
        },
        {
          title: "Spacer",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/8.+Spacer.mp4",
          id: "45",
        },
        {
          title: "Line",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/9.+Line.mp4",
          id: "46",
        },
        {
          title: "Map",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/10.+Map.mp4",
          id: "47",
        },
        {
          title: "Embed",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/11.+Embed.mp4",
          id: "48",
        },
        {
          title: "Icon Box",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/12.+Icon+Box.mp4",
          id: "49",
        },
        {
          title: "Counter",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/13.+Counter.mp4",
          id: "50",
        },
        {
          title: "Countdown",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/14.+Countdown.mp4",
          id: "51",
        },
        {
          title: "Tabs",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/15.+Tabs.mp4",
          id: "52",
        },
        {
          title: "Progress",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/16.+Progress.mp4",
          id: "53",
        },
        {
          title: "Accordion",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/17.+Accordion.mp4",
          id: "54",
        },
        {
          title: "Menu",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/18.+Menu.mp4",
          id: "55",
        },
        {
          title: "Gallery",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/19.+Gallery.mp4",
          id: "56",
        },
        {
          title: "Carousel",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/20.+Carousel.mp4",
          id: "57",
        },
        {
          title: "Rating",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/21.+Rating.mp4",
          id: "58",
        },
        {
          title: "Playlist",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/22.+Playlist.mp4",
          id: "59",
        },
        {
          title: "Table",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/23.+Table.mp4",
          id: "60",
        },
        {
          title: "Timeline",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/24.+Timeline.mp4",
          id: "61",
        },
        {
          title: "Switcher",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/25.+Switcher.mp4",
          id: "62",
        },
        {
          title: "Lottie",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/26.+Lottie.mp4",
          id: "63",
        },
        {
          title: "Login/register",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/27.+Login+register.mp4",
          id: "64",
        },
        {
          title: "Translation",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/28.+Translation.mp4",
          id: "65",
        },
        {
          title: "Alert",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/29.+Alert.mp4",
          id: "66",
        },
        {
          title: "Facebook",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/30.+Facebook.mp4",
          id: "67",
        },
        {
          title: "Twitter",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/31.+Twitter.mp4",
          id: "68",
        },
        {
          title: "Calendly",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/32.+Calendly.mp4",
          id: "69",
        },
        {
          title: "Comments",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/33.+Comments.mp4",
          id: "70",
        },
        {
          title: "Posts",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/34.+Posts.mp4",
          id: "71",
        },
        {
          title: "Assets",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/35.+Assets.mp4",
          id: "72",
        },
        {
          title: "User Elements",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/36.+User+Elements.mp4",
          id: "73",
        },
        {
          title: "Breadcrumbs",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/Breadcrumbs.mp4",
          id: "74",
        },
        {
          title: "Post Navigation",
          url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/8.+THE+ELEMENTS/Post+Navigation.mp4",
          id: "75",
        },
      ],
    },
  ],
  header: {
    src: "https://b-cloud.b-cdn.net/WordPress+Editor+Help+Videos/Getting-started-video-thumb.jpg",
    url: "https://b-cloud.b-cdn.net/Cloud+Editor+Help+Videos/1.+GET+STARTED/1.+Builder+Overview.mp4",
  },
  idHelpVideosIcons: {
    addElementsHelpVideo: "6",
    blocksLayoutsHelpVideo: "4",
    fontsHelpVideo: "11",
    formHelpVideo: "26",
  },
  showIcon: true,
};

export const demoConfig: Config = {
  mode: Modes.page,
  container: null,
  pageData: {
    id: 1,
    title: "Home",
    slug: "Home",
    status: "publish",
    data: {
      items: [],
    },
    dataVersion: 0,
    collectionType: {
      id: "1",
      title: "Pages",
    },
    fields: [],
  },
  projectData: {
    id: 1,
    selectedKit: "vnexmlshkihvcgsxmozgxzzdwsyvolvmhtne",
    selectedStyle: "kldugntsakdckzxhreidncqvgunudghrcuzv",
    styles: [
      {
        id: "kldugntsakdckzxhreidncqvgunudghrcuzv",
        title: "Default",
        colorPalette: [
          { id: "color1", hex: "#191b21" },
          { id: "color2", hex: "#142850" },
          { id: "color3", hex: "#239ddb" },
          { id: "color4", hex: "#66738d" },
          { id: "color5", hex: "#bde1f4" },
          { id: "color6", hex: "#eef0f2" },
          { id: "color7", hex: "#73777f" },
          { id: "color8", hex: "#ffffff" },
        ],
        fontStyles: [
          {
            deletable: "off",
            id: "paragraph",
            title: "Paragraph",
            fontFamily: "noto_serif",
            fontFamilyType: "google",
            fontSize: 16,
            fontSizeSuffix: "px",
            fontWeight: 300,
            lineHeight: 1.7,
            letterSpacing: 0,
            tabletFontSize: 15,
            tabletFontSizeSuffix: "px",
            tabletFontWeight: 300,
            tabletLineHeight: 1.6,
            tabletLetterSpacing: 0,
            mobileFontSize: 15,
            mobileFontSizeSuffix: "px",
            mobileFontWeight: 300,
            mobileLineHeight: 1.6,
            mobileLetterSpacing: 0,
          },
          {
            deletable: "off",
            id: "subtitle",
            title: "Subtitle",
            fontFamily: "noto_serif",
            fontFamilyType: "google",
            fontSize: 18,
            fontSizeSuffix: "px",
            fontWeight: 300,
            lineHeight: 1.5,
            letterSpacing: 0,
            tabletFontSize: 17,
            tabletFontSizeSuffix: "px",
            tabletFontWeight: 300,
            tabletLineHeight: 1.5,
            tabletLetterSpacing: 0,
            mobileFontSize: 17,
            mobileFontSizeSuffix: "px",
            mobileFontWeight: 300,
            mobileLineHeight: 1.5,
            mobileLetterSpacing: 0,
          },
          {
            deletable: "off",
            id: "abovetitle",
            title: "Above Title",
            fontFamily: "montserrat",
            fontFamilyType: "google",
            fontSize: 16,
            fontSizeSuffix: "px",
            fontWeight: 400,
            lineHeight: 1.7,
            letterSpacing: 2,
            tabletFontSize: 15,
            tabletFontSizeSuffix: "px",
            tabletFontWeight: 400,
            tabletLineHeight: 1.7,
            tabletLetterSpacing: 2,
            mobileFontSize: 13,
            mobileFontSizeSuffix: "px",
            mobileFontWeight: 400,
            mobileLineHeight: 1.7,
            mobileLetterSpacing: 2,
          },
          {
            deletable: "off",
            id: "heading1",
            title: "Heading 1",
            fontFamily: "montserrat",
            fontFamilyType: "google",
            fontSize: 56,
            fontSizeSuffix: "px",
            fontWeight: 200,
            lineHeight: 1.3,
            letterSpacing: -1.5,
            tabletFontSize: 40,
            tabletFontSizeSuffix: "px",
            tabletFontWeight: 200,
            tabletLineHeight: 1.3,
            tabletLetterSpacing: -1,
            mobileFontSize: 34,
            mobileFontSizeSuffix: "px",
            mobileFontWeight: 200,
            mobileLineHeight: 1.3,
            mobileLetterSpacing: -1,
          },
          {
            deletable: "off",
            id: "heading2",
            title: "Heading 2",
            fontFamily: "montserrat",
            fontFamilyType: "google",
            fontSize: 42,
            fontSizeSuffix: "px",
            fontWeight: 700,
            lineHeight: 1.3,
            letterSpacing: -1.5,
            tabletFontSize: 35,
            tabletFontSizeSuffix: "px",
            tabletFontWeight: 700,
            tabletLineHeight: 1.3,
            tabletLetterSpacing: -0.5,
            mobileFontSize: 29,
            mobileFontSizeSuffix: "px",
            mobileFontWeight: 700,
            mobileLineHeight: 1.3,
            mobileLetterSpacing: -0.5,
          },
          {
            deletable: "off",
            id: "heading3",
            title: "Heading 3",
            fontFamily: "montserrat",
            fontFamilyType: "google",
            fontSize: 32,
            fontSizeSuffix: "px",
            fontWeight: 600,
            lineHeight: 1.3,
            letterSpacing: -1,
            tabletFontSize: 27,
            tabletFontSizeSuffix: "px",
            tabletFontWeight: 600,
            tabletLineHeight: 1.3,
            tabletLetterSpacing: 0,
            mobileFontSize: 22,
            mobileFontSizeSuffix: "px",
            mobileFontWeight: 600,
            mobileLineHeight: 1.3,
            mobileLetterSpacing: 0,
          },
          {
            deletable: "off",
            id: "heading4",
            title: "Heading 4",
            fontFamily: "montserrat",
            fontFamilyType: "google",
            fontSize: 26,
            fontSizeSuffix: "px",
            fontWeight: 500,
            lineHeight: 1.4,
            letterSpacing: -1,
            tabletFontSize: 24,
            tabletFontSizeSuffix: "px",
            tabletFontWeight: 500,
            tabletLineHeight: 1.4,
            tabletLetterSpacing: 0,
            mobileFontSize: 21,
            mobileFontSizeSuffix: "px",
            mobileFontWeight: 500,
            mobileLineHeight: 1.4,
            mobileLetterSpacing: 0,
          },
          {
            deletable: "off",
            id: "heading5",
            title: "Heading 5",
            fontFamily: "montserrat",
            fontFamilyType: "google",
            fontSize: 20,
            fontSizeSuffix: "px",
            fontWeight: 500,
            lineHeight: 1.5,
            letterSpacing: 0,
            tabletFontSize: 19,
            tabletFontSizeSuffix: "px",
            tabletFontWeight: 500,
            tabletLineHeight: 1.4,
            tabletLetterSpacing: 0,
            mobileFontSize: 18,
            mobileFontSizeSuffix: "px",
            mobileFontWeight: 500,
            mobileLineHeight: 1.4,
            mobileLetterSpacing: 0,
          },
          {
            deletable: "off",
            id: "heading6",
            title: "Heading 6",
            fontFamily: "montserrat",
            fontFamilyType: "google",
            fontSize: 17,
            fontSizeSuffix: "px",
            fontWeight: 500,
            lineHeight: 1.5,
            letterSpacing: 0,
            tabletFontSize: 16,
            tabletFontSizeSuffix: "px",
            tabletFontWeight: 500,
            tabletLineHeight: 1.4,
            tabletLetterSpacing: 0,
            mobileFontSize: 16,
            mobileFontSizeSuffix: "px",
            mobileFontWeight: 500,
            mobileLineHeight: 1.4,
            mobileLetterSpacing: 0,
          },
          {
            deletable: "off",
            id: "button",
            title: "Button",
            fontFamily: "montserrat",
            fontFamilyType: "google",
            fontSize: 12,
            fontSizeSuffix: "px",
            fontWeight: 600,
            lineHeight: 1.8,
            letterSpacing: 3,
            tabletFontSize: 12,
            tabletFontSizeSuffix: "px",
            tabletFontWeight: 600,
            tabletLineHeight: 1.8,
            tabletLetterSpacing: 3,
            mobileFontSize: 12,
            mobileFontSizeSuffix: "px",
            mobileFontWeight: 600,
            mobileLineHeight: 1.8,
            mobileLetterSpacing: 3,
          },
        ],
      },
    ],
    extraFontStyles: [],
    font: "lato",
    fonts: {
      config: {
        data: [
          {
            kind: "webfonts#webfont",
            family: "Lato",
            category: "sans-serif",
            variants: [
              "100",
              "100italic",
              "300",
              "300italic",
              "regular",
              "italic",
              "700",
              "700italic",
              "900",
              "900italic",
            ],
            subsets: ["latin-ext", "latin"],
            version: "v15",
            lastModified: "2019-03-26",
            files: {
              100: "http://fonts.gstatic.com/s/lato/v15/S6u8w4BMUTPHh30wWyWrFCbw7A.ttf",
              300: "http://fonts.gstatic.com/s/lato/v15/S6u9w4BMUTPHh7USew-FGC_p9dw.ttf",
              700: "http://fonts.gstatic.com/s/lato/v15/S6u9w4BMUTPHh6UVew-FGC_p9dw.ttf",
              900: "http://fonts.gstatic.com/s/lato/v15/S6u9w4BMUTPHh50Xew-FGC_p9dw.ttf",
              "100italic": "http://fonts.gstatic.com/s/lato/v15/S6u-w4BMUTPHjxsIPy-vNiPg7MU0.ttf",
              "300italic": "http://fonts.gstatic.com/s/lato/v15/S6u_w4BMUTPHjxsI9w2PHA3s5dwt7w.ttf",
              regular: "http://fonts.gstatic.com/s/lato/v15/S6uyw4BMUTPHvxk6XweuBCY.ttf",
              italic: "http://fonts.gstatic.com/s/lato/v15/S6u8w4BMUTPHjxswWyWrFCbw7A.ttf",
              "700italic": "http://fonts.gstatic.com/s/lato/v15/S6u_w4BMUTPHjxsI5wqPHA3s5dwt7w.ttf",
              "900italic": "http://fonts.gstatic.com/s/lato/v15/S6u_w4BMUTPHjxsI3wiPHA3s5dwt7w.ttf",
            },
            brizyId: "uzrpsocdxtgrkbxjjxkchqcybpvpzsuvdlji",
          },
          {
            kind: "webfonts#webfont",
            family: "Overpass",
            category: "sans-serif",
            variants: [
              "100",
              "100italic",
              "200",
              "200italic",
              "300",
              "300italic",
              "regular",
              "italic",
              "600",
              "600italic",
              "700",
              "700italic",
              "800",
              "800italic",
              "900",
              "900italic",
            ],
            subsets: ["latin", "latin-ext"],
            version: "v4",
            lastModified: "2019-07-17",
            files: {
              100: "http://fonts.gstatic.com/s/overpass/v4/qFdB35WCmI96Ajtm81nGU97gxhcJk1s.ttf",
              200: "http://fonts.gstatic.com/s/overpass/v4/qFdA35WCmI96Ajtm81lqcv7K6BsAikI7.ttf",
              300: "http://fonts.gstatic.com/s/overpass/v4/qFdA35WCmI96Ajtm81kOcf7K6BsAikI7.ttf",
              600: "http://fonts.gstatic.com/s/overpass/v4/qFdA35WCmI96Ajtm81l6d_7K6BsAikI7.ttf",
              700: "http://fonts.gstatic.com/s/overpass/v4/qFdA35WCmI96Ajtm81kedv7K6BsAikI7.ttf",
              800: "http://fonts.gstatic.com/s/overpass/v4/qFdA35WCmI96Ajtm81kCdf7K6BsAikI7.ttf",
              900: "http://fonts.gstatic.com/s/overpass/v4/qFdA35WCmI96Ajtm81kmdP7K6BsAikI7.ttf",
              "100italic": "http://fonts.gstatic.com/s/overpass/v4/qFdD35WCmI96Ajtm81Gga7rqwjUMg1siNQ.ttf",
              "200italic": "http://fonts.gstatic.com/s/overpass/v4/qFdC35WCmI96Ajtm81GgaxbL4h8ij1I7LLE.ttf",
              "300italic": "http://fonts.gstatic.com/s/overpass/v4/qFdC35WCmI96Ajtm81Gga3LI4h8ij1I7LLE.ttf",
              regular: "http://fonts.gstatic.com/s/overpass/v4/qFdH35WCmI96Ajtm82GiWdrCwwcJ.ttf",
              italic: "http://fonts.gstatic.com/s/overpass/v4/qFdB35WCmI96Ajtm81GgU97gxhcJk1s.ttf",
              "600italic": "http://fonts.gstatic.com/s/overpass/v4/qFdC35WCmI96Ajtm81GgawbO4h8ij1I7LLE.ttf",
              "700italic": "http://fonts.gstatic.com/s/overpass/v4/qFdC35WCmI96Ajtm81Gga2LP4h8ij1I7LLE.ttf",
              "800italic": "http://fonts.gstatic.com/s/overpass/v4/qFdC35WCmI96Ajtm81Gga37M4h8ij1I7LLE.ttf",
              "900italic": "http://fonts.gstatic.com/s/overpass/v4/qFdC35WCmI96Ajtm81Gga1rN4h8ij1I7LLE.ttf",
            },
            brizyId: "qwhwsomltrpyogspgbomkxquvqsqfdlvcnfo",
          },
          {
            kind: "webfonts#webfont",
            family: "Red Hat Text",
            category: "sans-serif",
            variants: ["regular", "italic", "500", "500italic", "700", "700italic"],
            subsets: ["latin", "latin-ext"],
            version: "v1",
            lastModified: "2019-07-26",
            files: {
              500: "http://fonts.gstatic.com/s/redhattext/v1/RrQIbohi_ic6B3yVSzGBrMxYm4QIG-eFNVmULg.ttf",
              700: "http://fonts.gstatic.com/s/redhattext/v1/RrQIbohi_ic6B3yVSzGBrMxY04IIG-eFNVmULg.ttf",
              regular: "http://fonts.gstatic.com/s/redhattext/v1/RrQXbohi_ic6B3yVSzGBrMxgb60sE8yZPA.ttf",
              italic: "http://fonts.gstatic.com/s/redhattext/v1/RrQJbohi_ic6B3yVSzGBrMxQbacoMcmJPECN.ttf",
              "500italic": "http://fonts.gstatic.com/s/redhattext/v1/RrQKbohi_ic6B3yVSzGBrMxQbZ_cGO2BF1yELmgy.ttf",
              "700italic": "http://fonts.gstatic.com/s/redhattext/v1/RrQKbohi_ic6B3yVSzGBrMxQbZ-UHu2BF1yELmgy.ttf",
            },
            brizyId: "eytgthrgfzlrrzxlhynabspndabldgdbdjnm",
          },
          {
            kind: "webfonts#webfont",
            family: "DM Serif Text",
            category: "serif",
            variants: ["regular", "italic"],
            subsets: ["latin", "latin-ext"],
            version: "v3",
            lastModified: "2019-07-16",
            files: {
              regular: "http://fonts.gstatic.com/s/dmseriftext/v3/rnCu-xZa_krGokauCeNq1wWyafOPXHIJErY.ttf",
              italic: "http://fonts.gstatic.com/s/dmseriftext/v3/rnCw-xZa_krGokauCeNq1wWyWfGFWFAMArZKqQ.ttf",
            },
            brizyId: "pujmflqmocbjojknwlnidilgqedjzqftpnrv",
          },
          {
            kind: "webfonts#webfont",
            family: "Blinker",
            category: "sans-serif",
            variants: ["100", "200", "300", "regular", "600", "700", "800", "900"],
            subsets: ["latin", "latin-ext"],
            version: "v1",
            lastModified: "2019-07-26",
            files: {
              100: "http://fonts.gstatic.com/s/blinker/v1/cIf_MaFatEE-VTaP_E2hZEsCkIt9QQ.ttf",
              200: "http://fonts.gstatic.com/s/blinker/v1/cIf4MaFatEE-VTaP_OGARGEsnIJkWL4.ttf",
              300: "http://fonts.gstatic.com/s/blinker/v1/cIf4MaFatEE-VTaP_IWDRGEsnIJkWL4.ttf",
              600: "http://fonts.gstatic.com/s/blinker/v1/cIf4MaFatEE-VTaP_PGFRGEsnIJkWL4.ttf",
              700: "http://fonts.gstatic.com/s/blinker/v1/cIf4MaFatEE-VTaP_JWERGEsnIJkWL4.ttf",
              800: "http://fonts.gstatic.com/s/blinker/v1/cIf4MaFatEE-VTaP_ImHRGEsnIJkWL4.ttf",
              900: "http://fonts.gstatic.com/s/blinker/v1/cIf4MaFatEE-VTaP_K2GRGEsnIJkWL4.ttf",
              regular: "http://fonts.gstatic.com/s/blinker/v1/cIf9MaFatEE-VTaPxCmrYGkHgIs.ttf",
            },
            brizyId: "yhkoopjikembswaygkzktfmiiashwjcrvbxr",
          },
          {
            kind: "webfonts#webfont",
            family: "Aleo",
            category: "serif",
            variants: ["300", "300italic", "regular", "italic", "700", "700italic"],
            subsets: ["latin", "latin-ext"],
            version: "v3",
            lastModified: "2019-07-16",
            files: {
              300: "http://fonts.gstatic.com/s/aleo/v3/c4mg1nF8G8_syKbr9DVDno985KM.ttf",
              700: "http://fonts.gstatic.com/s/aleo/v3/c4mg1nF8G8_syLbs9DVDno985KM.ttf",
              "300italic": "http://fonts.gstatic.com/s/aleo/v3/c4mi1nF8G8_swAjxeDdJmq159KOnWA.ttf",
              regular: "http://fonts.gstatic.com/s/aleo/v3/c4mv1nF8G8_s8ArD0D1ogoY.ttf",
              italic: "http://fonts.gstatic.com/s/aleo/v3/c4mh1nF8G8_swAjJ1B9tkoZl_Q.ttf",
              "700italic": "http://fonts.gstatic.com/s/aleo/v3/c4mi1nF8G8_swAjxaDBJmq159KOnWA.ttf",
            },
            brizyId: "ucgecsrbcjkpsfctgzwsocokuydcdgiubroh",
          },
          {
            kind: "webfonts#webfont",
            family: "Nunito",
            category: "sans-serif",
            variants: [
              "200",
              "200italic",
              "300",
              "300italic",
              "regular",
              "italic",
              "600",
              "600italic",
              "700",
              "700italic",
              "800",
              "800italic",
              "900",
              "900italic",
            ],
            subsets: ["latin", "vietnamese", "latin-ext"],
            version: "v11",
            lastModified: "2019-07-22",
            files: {
              200: "http://fonts.gstatic.com/s/nunito/v11/XRXW3I6Li01BKofA-sekZuHJeTsfDQ.ttf",
              300: "http://fonts.gstatic.com/s/nunito/v11/XRXW3I6Li01BKofAnsSkZuHJeTsfDQ.ttf",
              600: "http://fonts.gstatic.com/s/nunito/v11/XRXW3I6Li01BKofA6sKkZuHJeTsfDQ.ttf",
              700: "http://fonts.gstatic.com/s/nunito/v11/XRXW3I6Li01BKofAjsOkZuHJeTsfDQ.ttf",
              800: "http://fonts.gstatic.com/s/nunito/v11/XRXW3I6Li01BKofAksCkZuHJeTsfDQ.ttf",
              900: "http://fonts.gstatic.com/s/nunito/v11/XRXW3I6Li01BKofAtsGkZuHJeTsfDQ.ttf",
              "200italic": "http://fonts.gstatic.com/s/nunito/v11/XRXQ3I6Li01BKofIMN5MZ-vNWz4PDWtj.ttf",
              "300italic": "http://fonts.gstatic.com/s/nunito/v11/XRXQ3I6Li01BKofIMN4oZOvNWz4PDWtj.ttf",
              regular: "http://fonts.gstatic.com/s/nunito/v11/XRXV3I6Li01BKof4MuyAbsrVcA.ttf",
              italic: "http://fonts.gstatic.com/s/nunito/v11/XRXX3I6Li01BKofIMOaETM_FcCIG.ttf",
              "600italic": "http://fonts.gstatic.com/s/nunito/v11/XRXQ3I6Li01BKofIMN5cYuvNWz4PDWtj.ttf",
              "700italic": "http://fonts.gstatic.com/s/nunito/v11/XRXQ3I6Li01BKofIMN44Y-vNWz4PDWtj.ttf",
              "800italic": "http://fonts.gstatic.com/s/nunito/v11/XRXQ3I6Li01BKofIMN4kYOvNWz4PDWtj.ttf",
              "900italic": "http://fonts.gstatic.com/s/nunito/v11/XRXQ3I6Li01BKofIMN4AYevNWz4PDWtj.ttf",
            },
            brizyId: "ppzycxqtiwtmjnfpbfluoynrnnfviuerjczz",
          },
          {
            kind: "webfonts#webfont",
            family: "Knewave",
            category: "display",
            variants: ["regular"],
            subsets: ["latin", "latin-ext"],
            version: "v8",
            lastModified: "2019-07-16",
            files: {
              regular: "http://fonts.gstatic.com/s/knewave/v8/sykz-yx0lLcxQaSItSq9-trEvlQ.ttf",
            },
            brizyId: "jojwyelvgkjknbgrosxcdphkpqfcczzdlcen",
          },
          {
            kind: "webfonts#webfont",
            family: "Palanquin",
            category: "sans-serif",
            variants: ["100", "200", "300", "regular", "500", "600", "700"],
            subsets: ["devanagari", "latin", "latin-ext"],
            version: "v5",
            lastModified: "2019-07-16",
            files: {
              100: "http://fonts.gstatic.com/s/palanquin/v5/9XUhlJ90n1fBFg7ceXwUEltI7rWmZzTH.ttf",
              200: "http://fonts.gstatic.com/s/palanquin/v5/9XUilJ90n1fBFg7ceXwUvnpoxJuqbi3ezg.ttf",
              300: "http://fonts.gstatic.com/s/palanquin/v5/9XUilJ90n1fBFg7ceXwU2nloxJuqbi3ezg.ttf",
              500: "http://fonts.gstatic.com/s/palanquin/v5/9XUilJ90n1fBFg7ceXwUgnhoxJuqbi3ezg.ttf",
              600: "http://fonts.gstatic.com/s/palanquin/v5/9XUilJ90n1fBFg7ceXwUrn9oxJuqbi3ezg.ttf",
              700: "http://fonts.gstatic.com/s/palanquin/v5/9XUilJ90n1fBFg7ceXwUyn5oxJuqbi3ezg.ttf",
              regular: "http://fonts.gstatic.com/s/palanquin/v5/9XUnlJ90n1fBFg7ceXwsdlFMzLC2Zw.ttf",
            },
            brizyId: "xnikbaszrjutnnfixmtprduwstoziivqiflp",
          },
          {
            kind: "webfonts#webfont",
            family: "Palanquin Dark",
            category: "sans-serif",
            variants: ["regular", "500", "600", "700"],
            subsets: ["devanagari", "latin", "latin-ext"],
            version: "v6",
            lastModified: "2019-07-16",
            files: {
              500: "http://fonts.gstatic.com/s/palanquindark/v6/xn76YHgl1nqmANMB-26xC7yuF8Z6ZW41fcvN2KT4.ttf",
              600: "http://fonts.gstatic.com/s/palanquindark/v6/xn76YHgl1nqmANMB-26xC7yuF8ZWYm41fcvN2KT4.ttf",
              700: "http://fonts.gstatic.com/s/palanquindark/v6/xn76YHgl1nqmANMB-26xC7yuF8YyY241fcvN2KT4.ttf",
              regular: "http://fonts.gstatic.com/s/palanquindark/v6/xn75YHgl1nqmANMB-26xC7yuF_6OTEo9VtfE.ttf",
            },
            brizyId: "gqzfchsrosvxegeymkyugyofaztsitibprrf",
          },
          {
            kind: "webfonts#webfont",
            family: "Roboto",
            category: "sans-serif",
            variants: [
              "100",
              "100italic",
              "300",
              "300italic",
              "regular",
              "italic",
              "500",
              "500italic",
              "700",
              "700italic",
              "900",
              "900italic",
            ],
            subsets: ["greek-ext", "latin", "cyrillic-ext", "vietnamese", "latin-ext", "greek", "cyrillic"],
            version: "v20",
            lastModified: "2019-07-24",
            files: {
              100: "http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1MmgWxPKTM1K9nz.ttf",
              300: "http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmSU5vAx05IsDqlA.ttf",
              500: "http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmEU9vAx05IsDqlA.ttf",
              700: "http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf",
              900: "http://fonts.gstatic.com/s/roboto/v20/KFOlCnqEu92Fr1MmYUtvAx05IsDqlA.ttf",
              "100italic": "http://fonts.gstatic.com/s/roboto/v20/KFOiCnqEu92Fr1Mu51QrIzcXLsnzjYk.ttf",
              "300italic": "http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TjARc9AMX6lJBP.ttf",
              regular: "http://fonts.gstatic.com/s/roboto/v20/KFOmCnqEu92Fr1Me5WZLCzYlKw.ttf",
              italic: "http://fonts.gstatic.com/s/roboto/v20/KFOkCnqEu92Fr1Mu52xPKTM1K9nz.ttf",
              "500italic": "http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51S7ABc9AMX6lJBP.ttf",
              "700italic": "http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TzBhc9AMX6lJBP.ttf",
              "900italic": "http://fonts.gstatic.com/s/roboto/v20/KFOjCnqEu92Fr1Mu51TLBBc9AMX6lJBP.ttf",
            },
            brizyId: "wrqenoprsynrjiyxmfoeuwqddlnomrxemeec",
          },
          {
            kind: "webfonts#webfont",
            family: "Oswald",
            category: "sans-serif",
            variants: ["200", "300", "regular", "500", "600", "700"],
            subsets: ["latin", "cyrillic-ext", "vietnamese", "latin-ext", "cyrillic"],
            version: "v24",
            lastModified: "2019-07-23",
            files: {
              200: "http://fonts.gstatic.com/s/oswald/v24/TK3_WkUHHAIjg75cFRf3bXL8LICs13FvgUFoZAaRliE.ttf",
              300: "http://fonts.gstatic.com/s/oswald/v24/TK3_WkUHHAIjg75cFRf3bXL8LICs169vgUFoZAaRliE.ttf",
              500: "http://fonts.gstatic.com/s/oswald/v24/TK3_WkUHHAIjg75cFRf3bXL8LICs18NvgUFoZAaRliE.ttf",
              600: "http://fonts.gstatic.com/s/oswald/v24/TK3_WkUHHAIjg75cFRf3bXL8LICs1y9ogUFoZAaRliE.ttf",
              700: "http://fonts.gstatic.com/s/oswald/v24/TK3_WkUHHAIjg75cFRf3bXL8LICs1xZogUFoZAaRliE.ttf",
              regular: "http://fonts.gstatic.com/s/oswald/v24/TK3_WkUHHAIjg75cFRf3bXL8LICs1_FvgUFoZAaRliE.ttf",
            },
            brizyId: "ehiobdhupkijoltxyucnkenojglortpsupmp",
          },
          {
            kind: "webfonts#webfont",
            family: "Oxygen",
            category: "sans-serif",
            variants: ["300", "regular", "700"],
            subsets: ["latin", "latin-ext"],
            version: "v9",
            lastModified: "2019-07-22",
            files: {
              300: "http://fonts.gstatic.com/s/oxygen/v9/2sDcZG1Wl4LcnbuCJW8Db2-4C7wFZQ.ttf",
              700: "http://fonts.gstatic.com/s/oxygen/v9/2sDcZG1Wl4LcnbuCNWgDb2-4C7wFZQ.ttf",
              regular: "http://fonts.gstatic.com/s/oxygen/v9/2sDfZG1Wl4Lcnbu6iUcnZ0SkAg.ttf",
            },
            brizyId: "gzhhqjoyiaozuhrmbylqeknkdaqtxfdynaqt",
          },
          {
            kind: "webfonts#webfont",
            family: "Playfair Display",
            category: "serif",
            variants: ["regular", "italic", "700", "700italic", "900", "900italic"],
            subsets: ["latin", "vietnamese", "latin-ext", "cyrillic"],
            version: "v15",
            lastModified: "2019-07-22",
            files: {
              700: "http://fonts.gstatic.com/s/playfairdisplay/v15/nuFlD-vYSZviVYUb_rj3ij__anPXBYf9pWkU5xxiJKY.ttf",
              900: "http://fonts.gstatic.com/s/playfairdisplay/v15/nuFlD-vYSZviVYUb_rj3ij__anPXBb__pWkU5xxiJKY.ttf",
              regular: "http://fonts.gstatic.com/s/playfairdisplay/v15/nuFiD-vYSZviVYUb_rj3ij__anPXPTvSgWE_-xU.ttf",
              italic: "http://fonts.gstatic.com/s/playfairdisplay/v15/nuFkD-vYSZviVYUb_rj3ij__anPXDTnYhUM66xV7PQ.ttf",
              "700italic":
                "http://fonts.gstatic.com/s/playfairdisplay/v15/nuFnD-vYSZviVYUb_rj3ij__anPXDTngOWwe4z5nNKaV_w.ttf",
              "900italic":
                "http://fonts.gstatic.com/s/playfairdisplay/v15/nuFnD-vYSZviVYUb_rj3ij__anPXDTngAW4e4z5nNKaV_w.ttf",
            },
            brizyId: "bvbbabnggnnjzvtleuwdrnfuvssxrgeovjan",
          },
          {
            kind: "webfonts#webfont",
            family: "Fira Sans",
            category: "sans-serif",
            variants: [
              "100",
              "100italic",
              "200",
              "200italic",
              "300",
              "300italic",
              "regular",
              "italic",
              "500",
              "500italic",
              "600",
              "600italic",
              "700",
              "700italic",
              "800",
              "800italic",
              "900",
              "900italic",
            ],
            subsets: ["greek-ext", "latin", "cyrillic-ext", "vietnamese", "latin-ext", "greek", "cyrillic"],
            version: "v10",
            lastModified: "2019-07-22",
            files: {
              100: "http://fonts.gstatic.com/s/firasans/v10/va9C4kDNxMZdWfMOD5Vn9IjOazP3dUTP.ttf",
              200: "http://fonts.gstatic.com/s/firasans/v10/va9B4kDNxMZdWfMOD5VnWKnuQR37fF3Wlg.ttf",
              300: "http://fonts.gstatic.com/s/firasans/v10/va9B4kDNxMZdWfMOD5VnPKruQR37fF3Wlg.ttf",
              500: "http://fonts.gstatic.com/s/firasans/v10/va9B4kDNxMZdWfMOD5VnZKvuQR37fF3Wlg.ttf",
              600: "http://fonts.gstatic.com/s/firasans/v10/va9B4kDNxMZdWfMOD5VnSKzuQR37fF3Wlg.ttf",
              700: "http://fonts.gstatic.com/s/firasans/v10/va9B4kDNxMZdWfMOD5VnLK3uQR37fF3Wlg.ttf",
              800: "http://fonts.gstatic.com/s/firasans/v10/va9B4kDNxMZdWfMOD5VnMK7uQR37fF3Wlg.ttf",
              900: "http://fonts.gstatic.com/s/firasans/v10/va9B4kDNxMZdWfMOD5VnFK_uQR37fF3Wlg.ttf",
              "100italic": "http://fonts.gstatic.com/s/firasans/v10/va9A4kDNxMZdWfMOD5VvkrCqYTfVcFTPj0s.ttf",
              "200italic": "http://fonts.gstatic.com/s/firasans/v10/va9f4kDNxMZdWfMOD5VvkrAGQBf_XljGllLX.ttf",
              "300italic": "http://fonts.gstatic.com/s/firasans/v10/va9f4kDNxMZdWfMOD5VvkrBiQxf_XljGllLX.ttf",
              regular: "http://fonts.gstatic.com/s/firasans/v10/va9E4kDNxMZdWfMOD5VfkILKSTbndQ.ttf",
              italic: "http://fonts.gstatic.com/s/firasans/v10/va9C4kDNxMZdWfMOD5VvkojOazP3dUTP.ttf",
              "500italic": "http://fonts.gstatic.com/s/firasans/v10/va9f4kDNxMZdWfMOD5VvkrA6Qhf_XljGllLX.ttf",
              "600italic": "http://fonts.gstatic.com/s/firasans/v10/va9f4kDNxMZdWfMOD5VvkrAWRRf_XljGllLX.ttf",
              "700italic": "http://fonts.gstatic.com/s/firasans/v10/va9f4kDNxMZdWfMOD5VvkrByRBf_XljGllLX.ttf",
              "800italic": "http://fonts.gstatic.com/s/firasans/v10/va9f4kDNxMZdWfMOD5VvkrBuRxf_XljGllLX.ttf",
              "900italic": "http://fonts.gstatic.com/s/firasans/v10/va9f4kDNxMZdWfMOD5VvkrBKRhf_XljGllLX.ttf",
            },
            brizyId: "wndeuiwznzaqgsugjnojbhzjhjwtryegciis",
          },
          {
            kind: "webfonts#webfont",
            family: "Abril Fatface",
            category: "display",
            variants: ["regular"],
            subsets: ["latin", "latin-ext"],
            version: "v11",
            lastModified: "2019-07-17",
            files: {
              regular: "http://fonts.gstatic.com/s/abrilfatface/v11/zOL64pLDlL1D99S8g8PtiKchm-BsjOLhZBY.ttf",
            },
            brizyId: "fbyhozjmiqseimmgxerwiucacmaaljqitrdc",
          },
          {
            kind: "webfonts#webfont",
            family: "Comfortaa",
            category: "display",
            variants: ["300", "regular", "500", "600", "700"],
            subsets: ["latin", "cyrillic-ext", "vietnamese", "latin-ext", "greek", "cyrillic"],
            version: "v23",
            lastModified: "2019-07-17",
            files: {
              300: "http://fonts.gstatic.com/s/comfortaa/v23/1Pt_g8LJRfWJmhDAuUsSQamb1W0lwk4S4TbMPrQVIT9c2c8.ttf",
              500: "http://fonts.gstatic.com/s/comfortaa/v23/1Pt_g8LJRfWJmhDAuUsSQamb1W0lwk4S4VrMPrQVIT9c2c8.ttf",
              600: "http://fonts.gstatic.com/s/comfortaa/v23/1Pt_g8LJRfWJmhDAuUsSQamb1W0lwk4S4bbLPrQVIT9c2c8.ttf",
              700: "http://fonts.gstatic.com/s/comfortaa/v23/1Pt_g8LJRfWJmhDAuUsSQamb1W0lwk4S4Y_LPrQVIT9c2c8.ttf",
              regular: "http://fonts.gstatic.com/s/comfortaa/v23/1Pt_g8LJRfWJmhDAuUsSQamb1W0lwk4S4WjMPrQVIT9c2c8.ttf",
            },
            brizyId: "plspcdzrrelkhthvkmoocpwrtltvuzqcyraw",
          },
          {
            kind: "webfonts#webfont",
            family: "Kaushan Script",
            category: "handwriting",
            variants: ["regular"],
            subsets: ["latin", "latin-ext"],
            version: "v8",
            lastModified: "2019-07-17",
            files: {
              regular: "http://fonts.gstatic.com/s/kaushanscript/v8/vm8vdRfvXFLG3OLnsO15WYS5DF7_ytN3M48a.ttf",
            },
            brizyId: "simpmqjphttgbnwqaobwxuxoavrdlbpdjgzc",
          },
        ],
      },
    },
  },
  integrations: {
    form: {
      action: "/api/leads",
    },
  },
  urls: {
    compileTemplateIcons: "/api/icons",
  },
  dynamicContent: {
    groups: {
      [DCTypes.image]: [
        {
          label: "Featured Image",
          optgroup: [
            {
              label: "Custom",
              placeholder: `{{${PlaceholderType.FeaturedImage} size="custom"}}`,
            },
            {
              label: "Original",
              placeholder: `{{${PlaceholderType.FeaturedImage} size="master"}}`,
            },
          ],
          placeholder: `{{${PlaceholderType.FeaturedImage}}}`,
        },
      ],
      [DCTypes.link]: [],
    },
  },
  contentDefaults: {
    PostTitle: {
      textPopulation: `{{${PlaceholderType.Title}}}`,
      textPopulationEntityType: "",
      textPopulationEntityId: "",
    },
    PostContent: {
      textPopulation: `{{${PlaceholderType.Description}}}`,
      textPopulationEntityType: "",
      textPopulationEntityId: "",
    },
    Posts: {
      _version: 3,
      items: [
        {
          type: "Column",
          value: {
            _styles: ["posts--column"],
            items: [
              {
                type: "Wrapper",
                value: {
                  _styles: ["wrapper", "wrapper-postTitle", "wrapper-postTitle-posts", "wrapper-postTitle-posts-posts"],
                  items: [
                    {
                      type: "WPPostsTitle",
                      value: {
                        _styles: ["postTitle", "postTitle-posts", "postTitle-posts-posts"],
                      },
                    },
                  ],
                },
              },
              {
                type: "Cloneable",
                value: {
                  _styles: ["wrapper-clone", "wrapper-clone--button"],
                  items: [
                    {
                      type: "Button",
                      value: {
                        linkExternalBlank: "on",
                        _styles: ["button", "button--dynamic"],
                      },
                    },
                  ],
                },
              },
            ],
          },
        },
      ],
      source: EntityType.BLOG,
    },
  },
  ui: {
    help: helpVideos,
  },
};
