nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS']
        allow_headers: ['*']
        expose_headers: ['*']
        max_age: 3600
    paths:
        '^/': null
