name: "Build Documentation Image"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name"
        required: true
        default: "main"
        type: string

      version:
        description: "Version"
        required: true
        default: "v1.0.0"
        type: string


jobs:
  image-build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: docsMeta
        uses: docker/metadata-action@v5
        with:
          images: br1zy/builder-docs

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docusaurus
          file: ./docusaurus/Dockerfile
          push: true
          tags: br1zy/builder-docs:${{ inputs.version }}
          labels: ${{ steps.docsMeta.outputs.labels }}

      - name: Git Tags
        if: success()
        run: |
          git tag docs-${{ inputs.version }}
          git push origin --tags

      - name: Send custom message to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          username: "GitHub Bot"
          message: "New version of the documentation has been released ${{ inputs.version }}"
