name: "(¬‿¬)"

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Mode"
        required: true
        default: "pages"
        type: choice
        options:
          - pages
          - popup
          - story

      branch:
        description: "Branch name"
        required: true
        type: string

      version:
        description: "Version"
        required: true
        default: "2.0.1"
        type: string

      public_host:
        description: "CDN Domain name"
        required: true
        default: "https://cdn.brizylocal.com"
        type: string

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Typescript
        run: |
          npm run tsc:core

  deploy:
    needs: tests
    name: Build and deploy
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Create deploy
        run: npm run build:core -- -- --env PUBLIC_HOST=${{inputs.public_host}}/${{inputs.mode}}/${{inputs.version}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS S3
        if: success()
        run: |
          aws s3 cp packages/core/build s3://${{ secrets.AWS_BUCKET }}/${{ inputs.mode }}/${{ inputs.version }} --recursive

      - name: Git Tags
        if: success()
        run: |
          git tag v${{ inputs.version }}-${{ inputs.mode }}
          git push origin --tags
