name: "Pull Request Check Action"
on:
  pull_request:
    types: [closed, labeled]
jobs:
  tests:
    name: Tests
    runs-on: [self-hosted, office-server]
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    if: ${{ github.event.label.name == 'review' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: CommitLint
        run: |
          cd .github
          ./commit-check.sh ${{ github.event.pull_request.base.sha }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies...
        run: npm i

      - name: "Lint"
        run: npm run lint

      - name: Types checking
        run: npm run tsc
